### ISSUE TITLE
QWidget::windowHandle() call raises RuntimeError exception

### ISSUE THREAD

**Issue by jiban** [mborgerson/pyside6_qtads#34]
Hi there,
Thank you for the work you've done already.
I really appreciate it.

Recently, I wanted to use this PySide6 port of QT ADS for my project, and bumped into an exception.
```python
Traceback (most recent call last):
  File "C:\Users\jakej\Documents\workspace\pythonPlayground\venv\lib\site-packages\matplotlib\backends\backend_qt.py", line 495, in _draw_idle
    if self.height() < 0 or self.width() < 0:
  File "C:\Users\jakej\Documents\workspace\pythonPlayground\venv\lib\site-packages\matplotlib\backends\backend_qt.py", line 262, in showEvent
    window.screenChanged.connect(self._update_screen)
RuntimeError: Internal C++ object (PySide6.QtGui.QWindow) already deleted.
```

I was using [matplotlib](https://matplotlib.org/) chart in the dock.
The code that raised exception was following.
`venv/Lib/site-packages/matplotlib/backends/backend_qt.py`
```python
    def showEvent(self, event):
        # Set up correct pixel ratio, and connect to any signal changes for it,
        # once the window is shown (and thus has these attributes).
        window = self.window().windowHandle()
        window.screenChanged.connect(self._update_screen)
        self._update_screen(window.screen())
```

I investigated the code and found following.
When I changed the code like this, it worked.
```python
    def showEvent(self, event):
        # Set up correct pixel ratio, and connect to any signal changes for it,
        # once the window is shown (and thus has these attributes).
        dummy = self.window()  # <=== This is the code I inserted
        window = self.window().windowHandle()
        window.screenChanged.connect(self._update_screen)
        self._update_screen(window.screen())
```

However, I don't want to modify the code in matplotlib.
So I investigate more and suspected that the return value from QWidget.windowHandle() might be lost.
Finally I tried inserting following line in `bindings.xml`.
```xml
        <object-type name="CFloatingDockContainer">
            <!-- ... -->
            <declare-function signature="windowHandle()" return-type="QWindow"/>
            <!-- ... -->
        </object-type>
```

It works!

But I'm not sure if this correction is the way shiboken suggests because I'm not familiar with shiboken.
And I don't know the exact mechanism why this should be added though `CFloatingDockContainer` inherits `QWidget`.
The fact that a macro definition was used might make shiboken confusing.
```C
#include <QWidget>
#define tFloatingWidgetBase QWidget
```

Could you please look into this issue and clarify what the root cause of it?
Or we can just settle down on this `declare-function` solution.

Thank you for giving your precious attention on reading this issue.

Best regards,
Jake

**Comment by jiban** [comment]
Here is a simplified code that shows above issue.
[main_window.zip](https://github.com/mborgerson/pyside6_qtads/files/15373093/main_window.zip)

**Comment by VitalyName** [comment]
simple example to reproduce it without matplotlib can be found in first message of https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System/issues/579

**Comment by yuanxun-yx** [comment]
Hi @mborgerson, is it possible to solve this issue? @VitalyName mentioned a simple solution [here](https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System/issues/579#issuecomment-2149304213). Seems like a python wrapper issue with pointers. Thanks a lot.

**Comment by mborgerson** [comment]
Should be fixed now with @jiban's patch in #46 !

**Comment by jiban** [comment]
Thank you, @mborgerson!
